### ISSUE TITLE
Corrigir bug da tela amigo

### ISSUE THREAD

**Issue by ThiagoKakoSilveira** [ThiagoKakoSilveira/BibliotecaDaMae#1]
Tela amigo toda vez q renderiza diz que não encontra as fontes da página css sendo que está na tela... Erro que não impede o funcionamento do sistema porém mostra uma mensagem chata na tela

**Comment by CleberMaciel** [comment]
Foi somente trocar no xhtml Padrão o link que referenciava o webjars do font-awesome. Antes estava com <h:outputStylesheet name...." e foi trocado para  <link rel="..."... .
